import React from "react";
import Head from "next/head";

import WebMap from "components/web-map";
import Sidebar from "components/sidebar";
import ViewportPanel from "components/viewport-panel";
import { inspect } from "@xstate/inspect";
import { mapService } from "lib/map-state-machine";
// import { DataLayer } from "lib/mapbox-helpers";

// const persistedLayers: DataLayer[] = [
//   {
//     id: "086fcf",
//     name: "layer-1",
//     type: "raster",
//     urlType: "xyz",
//     url: "http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga",
//     sourceLayer: "",
//   },
// ];

if (typeof window !== "undefined" && process.env.NODE_ENV !== "production") {
  inspect({
    iframe: false,
  });

  mapService.start();
}

export default function Home() {
  return (
    <div className="h-full relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute w-full h-full">
        <WebMap className="h-full w-full inset-0" />
        <Sidebar />
        <ViewportPanel />
      </div>
    </div>
  );
}
