import React from "react";
import Head from "next/head";

import WebMap from "components/web-map";
import Sidebar from "components/sidebar";
import ViewportPanel from "components/viewport-panel";
import { inspect } from "@xstate/inspect";
import { MapContext, mapMachine, mapService } from "machines/mapbox-map";
import { State } from "xstate";

if (typeof window !== "undefined") {
  if (process.env.NODE_ENV !== "production") inspect({ iframe: false });

  const ctx = localStorage.getItem("state");

  const nextContext = ctx
    ? (JSON.parse(ctx) as MapContext)
    : mapMachine.initialState.context;

  console.log("Restore from persisted state");
  console.log(nextContext);

  mapService.start(State.from(mapMachine.initialState, nextContext));
}

export default function Home() {
  return (
    <div className="h-full relative">
      <Head>
        <title>Web Tiles Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <div className="absolute w-full h-full">
        <WebMap className="h-full w-full inset-0" />
        <Sidebar />
        <ViewportPanel />
      </div>
    </div>
  );
}
