import React from "react";
import Head from "next/head";

import WebMap from "components/web-map";
import Sidebar from "components/sidebar";
import ViewportPanel from "components/viewport-panel";
import { inspect } from "@xstate/inspect";
import { MapContext, mapMachine, mapService } from "lib/map-state-machine";
import { State } from "xstate";

if (typeof window !== "undefined") {
  if (process.env.NODE_ENV !== "production") inspect({ iframe: false });

  const ctx = localStorage.getItem("state");

  const nextContext = ctx
    ? (JSON.parse(ctx) as MapContext)
    : mapMachine.initialState.context;

  console.log("Restore from persisted state");
  console.log(nextContext);

  mapService.start(State.from(mapMachine.initialState, nextContext));
}

export default function Home() {
  return (
    <div className="h-full relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute w-full h-full">
        <WebMap className="h-full w-full inset-0" />
        <Sidebar />
        <ViewportPanel />
      </div>
    </div>
  );
}
